  name: Run robs script

  on:
    push:
      branches:
        - main

  jobs:
    run_robs:
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Run robs script
        run: |
          chmod +x robs
          bash -xv ./test.bash
