  name: Run robs script

  on:
    push:
      branches:
        - main

  jobs:
    run_robs:
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # もし必要なライブラリがあれば requirements.txt に追加してください

      - name: Run robs script
        run: |
          chmod +x robs
          bash -xv ./test.bash
